package example;


/**
* example/Fibonacci.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/cesar/Downloads/corba-main/CorbaFiboInterface/src/fibonacci.idl
* lunes 9 de agosto de 2021 06:23:35 PM CDT
*/

public interface Fibonacci extends FibonacciOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Fibonacci
